<?php
namespace Enterface\UserBundle\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-16 at 13:20:51.
 */
class DefaultControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DefaultController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DefaultController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Enterface\UserBundle\Controller\DefaultController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        /*
        $view = "EnterfaceUserBundle:Default:index.html.twig";
        $name = "123";
        $params = array('name' => $name);
        $response = $this->createMock("Symfony\Component\HttpFoundation\Response");
        
        $template = $this->createMock('Symfony\Bundle\FrameworkBundle\Templating\EngineInterface');
        $template
            ->expects($this->once())
            ->method("renderResponse")
            ->with($view, [$params], null)
            ->will($this->returnValue($response));
        
        $container = $this->createMock("Symfony\Component\DependencyInjection\ContainerInterface");
        $container->expects($this->at(0))
            ->method("get")
            ->with("templating")
            ->will($this->returnValue($template));
        
        $controller = new DefaultController();
        $controller->setContainer($container);
        
        $this->assertSame($response, $controller->indexAction($params));
         */

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }
}
