<?php
namespace Enterface\UserBundle\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-16 at 13:21:10.
 */
class UserControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UserController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Enterface\UserBundle\Controller\UserController::loginAction
     */
    public function testLoginAction()
    {
        //deux tests : anonymous ou non
        /*
        $controller = $this->object;
        $user = new User;
        $output = $controller->loginAction();
        var_dump($output);
        */
        
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\UserBundle\Controller\UserController::profileAction
     * @todo   Implement testProfileAction().
     */
    public function testProfileAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\UserBundle\Controller\UserController::teamAction
     * @todo   Implement testTeamAction().
     */
    public function testTeamAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\UserBundle\Controller\UserController::logoutAction
     * @todo   Implement testLogoutAction().
     */
    public function testLogoutAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
