<?php
namespace Enterface\UserBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-16 at 13:22:23.
 */
class UserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Enterface\UserBundle\Entity\User::__construct
     */
    public function test__construct()
    {
        $myobject = $this->object;
        $myobject->__construct();
        $this->assertFalse($myobject->isEnabled());
        $this->assertFalse($myobject->isLocked());
        $this->assertFalse($myobject->isExpired());
        $this->assertNotEmpty($myobject->getRoles());
        $this->assertFalse($myobject->isCredentialsExpired());
        $this->assertNotNull($myobject->getSalt());
    }

    /**
     * @covers Enterface\UserBundle\Entity\User::setLastname
     */
    public function testSetLastname()
    {
        $user = $this->object;
        $user->setLastname("test_setLastname");
        $this->assertEquals('test_setLastname', $this->object->getLastname());
    }

    /**
     * @covers Enterface\UserBundle\Entity\User::getLastname
     */
    public function testGetLastname()
    {
        $user = $this->object;
        $user->setLastname("test_getLastname");
        $this->assertEquals('test_getLastname', $this->object->getLastname());
    }

    /**
     * @covers Enterface\UserBundle\Entity\User::setFirstname
     */
    public function testSetFirstname()
    {
        $user = $this->object;
        $user->setFirstname("test_setFirstname");
        $this->assertEquals('test_setFirstname', $this->object->getFirstname());
    }

    /**
     * @covers Enterface\UserBundle\Entity\User::getFirstname
     */
    public function testGetFirstname()
    {
        $user = $this->object;
        $user->setFirstname("test_getFirstname");
        $this->assertEquals('test_getFirstname', $this->object->getFirstname());
    }

    /**
     * @covers Enterface\UserBundle\Entity\User::setTitle
     */
    public function testSetTitle()
    {
        $user = $this->object;
        $user->setTitle("test_setTitle");
        $this->assertEquals('test_setTitle', $this->object->getTitle());
    }

    /**
     * @covers Enterface\UserBundle\Entity\User::getTitle
     */
    public function testGetTitle()
    {
        $user = $this->object;
        $user->setTitle("test_getTitle");
        $this->assertEquals('test_getTitle', $this->object->getTitle());
    }

    /**
     * @covers Enterface\UserBundle\Entity\User::setAdress
     */
    public function testSetAdress()
    {
        $user = $this->object;
        $user->setAdress("test_setAdress");
        $this->assertEquals('test_setAdress', $this->object->getAdress());
    }

    /**
     * @covers Enterface\UserBundle\Entity\User::getAdress
     */
    public function testGetAdress()
    {
        $user = $this->object;
        $user->setAdress("test_getAdress");
        $this->assertEquals('test_getAdress', $this->object->getAdress());
    }

    /**
     * @covers Enterface\UserBundle\Entity\User::setCompany
     */
    public function testSetCompany()
    {
        $user = $this->object;
        $user->setCompany("test_setCompany");
        $this->assertEquals('test_setCompany', $this->object->getCompany());
    }

    /**
     * @covers Enterface\UserBundle\Entity\User::getCompany
     */
    public function testGetCompany()
    {
        $user = $this->object;
        $user->setCompany("test_getCompany");
        $this->assertEquals('test_getCompany', $this->object->getCompany());
    }

    /**
     * @covers Enterface\UserBundle\Entity\User::setCredit
     */
    public function testSetCredit()
    {
        $user = $this->object;
        $user->setCredit(12345);
        $this->assertEquals(12345, $this->object->getCredit());
    }

    /**
     * @covers Enterface\UserBundle\Entity\User::getCredit
     */
    public function testGetCredit()
    {
        $user = $this->object;
        $user->setCredit(54321);
        $this->assertEquals(54321, $this->object->getCredit());
    }
}
