#!/bin/bash
USAGE="USAGE: $0 [user_directory]"

if ( [ "1$1" == "1" ] ); 
then
  echo $USAGE;
  exit 1;
fi

DIR=$1

if ! [ -d $DIR ];
then
  echo "repertoire inexistant";
  exit 2;
fi

if ! [ -f $DIR/1.jpg ];
then
  echo "fichier 1.jpg inexistant";
  exit 3;
fi

docker run --rm -v $DIR:/home vertebrae 
