<?php
namespace Enterface\ServiceBundle\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-16 at 13:18:57.
 */
class ServicesControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ServicesController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ServicesController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::cleoAction
     * @todo   Implement testCleoAction().
     */
    public function testCleoAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
    public function downloadResultAction($file)
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
    
    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::realtreatmentAction
     * @todo   Implement testRealtreatmentAction().
     */
    public function testRealtreatmentAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::cleotreatmentAction
     * @todo   Implement testCleotreatmentAction().
     */
    public function testCleotreatmentAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::keratoAction
     * @todo   Implement testKeratoAction().
     */
    public function testKeratoAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::keratotreatmentAction
     * @todo   Implement testKeratotreatmentAction().
     */
    public function testKeratotreatmentAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::RealTimeMotionAction
     * @todo   Implement testRealTimeMotionAction().
     */
    public function testRealTimeMotionAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::Reconstruction3DAction
     * @todo   Implement testReconstruction3DAction().
     */
    public function testReconstruction3DAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::VertebraMobilityAction
     * @todo   Implement testVertebraMobilityAction().
     */
    public function testVertebraMobilityAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::VertebraSegmentationAction
     * @todo   Implement testVertebraSegmentationAction().
     */
    public function testVertebraSegmentationAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::TennistrackingAction
     * @todo   Implement testTennistrackingAction().
     */
    public function testTennistrackingAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::tennistreatmentAction
     * @todo   Implement testTennistreatmentAction().
     */
    public function testTennistreatmentAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::CardiotrackingAction
     * @todo   Implement testCardiotrackingAction().
     */
    public function testCardiotrackingAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::TrackingtreatmentAction
     * @todo   Implement testTrackingtreatmentAction().
     */
    public function testTrackingtreatmentAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::testCPPAction
     * @todo   Implement testTestCPPAction().
     */
    public function testTestCPPAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::testUploadCPPAction
     * @todo   Implement testTestUploadCPPAction().
     */
    public function testTestUploadCPPAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Enterface\ServiceBundle\Controller\ServicesController::segmentationAction
     * @todo   Implement testSegmentationAction().
     */
    public function testSegmentationAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
