#!/bin/bash
USAGE="USAGE: $0 [user_directory]"

if ( [ "1$1" == "1" ] ); 
then
  echo $USAGE;
  exit 1;
fi

DIR=$1

if ! [ -d $DIR ];
then
  echo "repertoire inexistant";
  exit 2;
fi

if ! [ -f $DIR/2.avi ];
then
  echo "fichier 2.avi inexistant";
  exit 3;
fi

target_file="../2.avi"

cd $DIR

mkdir -p output
cd output
/root/maintracking $target_file save || exit 1

ffmpeg -i Result.mpeg Results.webm
rm -f Result.mpeg

cd ..
find output -type f -exec chmod 644 \{\} \;
find output -type d -exec chmod 755 \{\} \;

chown -R output --reference 2.avi

