<?php
namespace Enterface\UserBundle\Form;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Forms;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-16 at 13:22:52.
 */
class RegistrationTypeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RegistrationType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RegistrationType;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Enterface\UserBundle\Form\RegistrationType::buildForm
     * @todo   Implement testBuildForm().
     */
    public function testBuildForm()
    {
        $builder = Forms::createFormFactory()->createBuilder();
        $form = $this->object;
        $form->buildForm($builder, array());
        $this->assertTrue( $builder->has("title") );
        $this->assertTrue( $builder->has("firstname") );
        $this->assertTrue( $builder->has("lastname") );
        $this->assertTrue( $builder->has("company") );
        $this->assertTrue( $builder->has("adress") );
    }

    /**
     * @covers Enterface\UserBundle\Form\RegistrationType::getParent
     */
    public function testGetParent()
    {
        $this->assertEquals('fos_user_registration', $this->object->getParent());
    }

    /**
     * @covers Enterface\UserBundle\Form\RegistrationType::getName
     */
    public function testGetName()
    {
        $this->assertEquals('enterface_user_registration', $this->object->getName());
    }
}
