<?php

namespace Enterface\UserBundle\Command;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-16 at 13:20:34.
 */
class CreateUserCommandTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var CreateUserCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CreateUserCommand;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testCreateUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
