<?php
namespace Enterface\UserBundle;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-16 at 14:03:43.
 */
class EnterfaceUserBundleTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var EnterfaceUserBundle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EnterfaceUserBundle;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Enterface\UserBundle\EnterfaceUserBundle::getParent
     */
    public function testGetParent()
    {
        $this->assertEquals('FOSUserBundle', $this->object->getParent());
    }
}
