# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

#services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    app.form.registration:
        class: Enterface\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: enterface_user_registration }
    app.form.profile:
        class: Enterface\UserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: enterface_user_profile }
            
    yosimitso_workingforum_smiley:
        class: Yosimitso\WorkingForumBundle\Twig\Extension\SmileyTwigExtension
        tags:
            -  { name: twig.extension }
        arguments: 
            request: "@request_stack"
            asset: "@twig.extension.assets"
        
    yosimitso_workingforum_quote:
        class: Yosimitso\WorkingForumBundle\Twig\Extension\QuoteTwigExtension
        tags:
            -  { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"
            trans: "@translator"
    yosimitso_workingforum_config:
        class: Yosimitso\WorkingForumBundle\Twig\Extension\ConfigurationTwigExtension
        tags:
            - { name: twig.extension }
        arguments:
            themeColor: "%yosimitso_working_forum.theme_color%"
    yosimitso_workingforum_authorization:
        class: Yosimitso\WorkingForumBundle\Security\Authorization
        arguments :
            securityChecker: "@security.authorization_checker"
            tokenStorage: "@security.token_storage"
            allowAnonymous: "%yosimitso_working_forum.allow_anonymous_read%"

