enterface_service_homepage:
    path:     /
    defaults: { _controller: EnterfaceServiceBundle:Default:index }

#enterface_service_to:
#    path:     /to/{id}
#    defaults: { _controller: EnterfaceServiceBundle:Default:to }

# add by eladoui----------------------------------------------------------------------------
enterface_service_cleoperso:
    path:     /cleoperso
    defaults: { _controller: EnterfaceServiceBundle:Services:cleoperso }
  
enterface_service_cleotreatmentperso:
    path:     /cleotreatmentperso
    defaults: { _controller: EnterfaceServiceBundle:Services:cleotreatmentperso }

enterface_service_showCleoperso:
    path:     /showCleoperso/ {var1}/{var2}/{var3}
    defaults: { _controller: EnterfaceServiceBundle:Services:showCleoperso }

enterface_service_showCleoadv:
    path:     /showCleoadv
    defaults: { _controller: EnterfaceServiceBundle:Services:showCleoadv }
    
enterface_service_cleotreatmentadv:
    path:     /cleotreatmentadv
    defaults: { _controller: EnterfaceServiceBundle:Services:cleotreatmentadv }

enterface_service_toolbox:
    path:     /toolbox
    defaults: { _controller: EnterfaceServiceBundle:Services:toolbox }

enterface_service_algotreatment1:
    path:     /algotreatment1
    defaults: { _controller: EnterfaceServiceBundle:Services:algotreatment1 }

enterface_service_algotreatment2:
    path:     /algotreatment2
    defaults: { _controller: EnterfaceServiceBundle:Services:algotreatment2 }

enterface_service_TiffViewer:
    path:     /TiffViewer
    defaults: { _controller: EnterfaceServiceBundle:Services:TiffViewer }

enterface_service_StlViewer:
    path:     /StlViewer
    defaults: { _controller: EnterfaceServiceBundle:Services:StlViewer }

enterface_service_mobility:
    path:     /mobility
    defaults: { _controller: EnterfaceServiceBundle:Services:mobility }
    
enterface_service_cles:
    path:     /cles
    defaults: { _controller: EnterfaceServiceBundle:Services:cles }
    
enterface_service_advancedvertebra:
    path:     /advancedvertebra
    defaults: { _controller: EnterfaceServiceBundle:Services:advancedvertebra }

enterface_service_vertebradetection:
    path:     /VertebraDetection
    defaults: { _controller: EnterfaceServiceBundle:Services:VertebraDetection }
    
enterface_service_vertebrapersonalized:
    path: /VertebraPersonalized
    defaults: { _controller: EnterfaceServiceBundle:Services:VertebraPersonalized }
    
enterface_service_showvertebraPersonalized:
    path: /ShowVertebraPersonalized
    defaults: { _controller: EnterfaceServiceBundle:Services:ShowVertebraPersonalized }

enterface_service_showvertebraAdvanced:
      path:     /showvertebraAdvanced
      defaults: { _controller: EnterfaceServiceBundle:Services:showvertebraAdvanced }
      
enterface_service_dicomviewer:
      path:     /dicomviewer
      defaults: { _controller: EnterfaceServiceBundle:Services:dicomviewer }

#-------------------------------------------------------------------------------------------
enterface_service_cleoadv:
    path:     /cleoadv
    defaults: { _controller: EnterfaceServiceBundle:Services:cleoadv }
    
enterface_service_cleo:
    path:     /cleo
    defaults: { _controller: EnterfaceServiceBundle:Services:cleo }
    
enterface_service_showcleo:
    path:     /showcleo
    defaults: { _controller: EnterfaceServiceBundle:Services:showCleo }

enterface_download_result:
    path:      /downloadresult/{file}
    defaults: { _controller: EnterfaceServiceBundle:Services:downloadResult }
    
enterface_service_cleotreatment:
    path:     /cleotreatment
    defaults: { _controller: EnterfaceServiceBundle:Services:cleotreatment }
    
#enterface_service_realmotion:
#    path:     /RealTimeMotion
#    defaults: { _controller: EnterfaceServiceBundle:Services:RealTimeMotion }

#enterface_service_tennis:
#    path:     /Tennistracking
#    defaults: { _controller: EnterfaceServiceBundle:Services:Tennistracking}
    
#enterface_service_tennistreatment:
#    path:     /tennistreatment
#    defaults: { _controller: EnterfaceServiceBundle:Services:tennistreatment}
    
#enterface_service_realtreatment:
#     path:     /realtreatment
#     defaults: { _controller: EnterfaceServiceBundle:Services:realtreatment }
    
#enterface_service_reconstruction:
#    path:     /Reconstruction3D
#    defaults: { _controller: EnterfaceServiceBundle:Services:Reconstruction3D }

#enterface_service_vertebramobility:
#    path:     /VertebraMobility
#    defaults: { _controller: EnterfaceServiceBundle:Services:VertebraMobility }
   
#enterface_service_kerato:
#    path:     /kerato
#    defaults: { _controller: EnterfaceServiceBundle:Services:kerato }
    
#enterface_service_keratotreatment:
#     path:     /keratotreatment
#     defaults: { _controller: EnterfaceServiceBundle:Services:keratotreatment }

#enterface_service_testCPP:
#    path:     /testCPP
#    defaults: { _controller: EnterfaceServiceBundle:Services:testCPP }
    
#enterface_service_testUploadCPP:
#    path:     /testUploadCPP
#    defaults: { _controller: EnterfaceServiceBundle:Services:testUploadCPP } 

enterface_service_vertebrasegmentation:
    path:     /VertebraSegmentation
    defaults: { _controller: EnterfaceServiceBundle:Services:VertebraSegmentation }
    
enterface_service_segmentation:
      path:     /segmentation
      defaults: { _controller: EnterfaceServiceBundle:Services:segmentation }
      
enterface_service_vertebrachange:
      path:     /vertebrachange
      defaults: { _controller: EnterfaceServiceBundle:Services:vertebrachange }
      
enterface_service_showvertebra:
    path:     /showvertebra
    defaults: { _controller: EnterfaceServiceBundle:Services:showVertebra }

enterface_service_showvertebraimage:
    path:     /vertebraimage/{a}/{b}/{c}/{file}
    defaults: { _controller: EnterfaceServiceBundle:Services:showVertebraImage }
    
enterface_service_cardiotracking:
      path:     /Cardiotracking
      defaults: { _controller: EnterfaceServiceBundle:Services:Cardiotracking }
      
enterface_service_tracking:
    path:       /Trackingtreatment
    defaults: { _controller: EnterfaceServiceBundle:Services:Trackingtreatment }
    
enterface_service_showtracking:
    path:       /showtracking
    defaults: { _controller: EnterfaceServiceBundle:Services:ShowTracking }

enterface_contact_sendMail:
    path:     /contactsendMail
    defaults: { _controller: EnterfaceServiceBundle:Services:sendmessage }

enterface_service_saveResults:
    path:     /saveResults/{name}
    defaults: { _controller: EnterfaceServiceBundle:Services:saveResults } 

enterface_service_restoreResults:
    path:     /restoreResults/{id}
    defaults: { _controller: EnterfaceServiceBundle:Services:restoreResults } 
    
enterface_mail_homepage:
    path:    /mail
    defaults: {_controller: EnterfaceServiceBundle:Default:mail }