services:
#    enterface_service.example:
#        class: Enterface\ServiceBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

#enterface_service.linkedin:
#    linkedin_Sidi_M:https://www.linkedin.com/in/sidi-ahmed-mahmoudi-95324534/