<?php
namespace Enterface\UserBundle\DependencyInjection;

use Symfony\Component\DependencyInjection\ContainerBuilder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-16 at 13:22:09.
 */
class EnterfaceUserExtensionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var EnterfaceUserExtension
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EnterfaceUserExtension;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Enterface\UserBundle\DependencyInjection\EnterfaceUserExtension::load
     */
    public function testLoad()
    {
        $container = new ContainerBuilder;
        $this->object->load(array(),$container);
        $this->assertStringMatchesFormat('%a',$this->object->getAlias());
    }
}
