#!/bin/bash
MYHOME=${1:-/home}
MYBASH=$2

echo MYHOME : $MYHOME

[ -d $MYHOME ] || exit 1;

RESULTID=$(basename $MYHOME)
USERID=$(basename $(dirname $MYHOME))

echo RESULTID = $RESULTID
echo USERID =$USERID

echo $RESULTID > $MYHOME/resultid.txt
echo $USERID > $MYHOME/userid.txt

if [ -z $MYBASH ]; then
  docker run -it --rm --privileged --cap-add SYS_ADMIN -v $MYHOME:/home mycrypto
else
  docker run -it --rm --privileged --cap-add SYS_ADMIN -v $MYHOME:/home mycrypto $MYBASH
fi
